# Generated by Django 2.2.5 on 2021-03-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('code', models.TextField()),
                ('lang_type', models.CharField(choices=[('PY', 'Python'), ('JS', 'JavaScript'), ('PHP', 'PHP'), ('JAVA', 'Java'), ('CPP', 'C++'), ('C', 'C'), ('CSHARP', 'C#'), ('R', 'R'), ('RBY', 'Ruby'), ('GO', 'Go'), ('SWIFT', 'Swift'), ('SQL', 'SQL')], max_length=12)),
                ('votes', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
