# Generated by Django 2.2.5 on 2021-04-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='lang_type',
            field=models.CharField(choices=[('PY', 'Python'), ('JS', 'JavaScript'), ('PHP', 'PHP'), ('JAVA', 'Java'), ('CPP', 'C++'), ('C', 'C'), ('SQL', 'SQL')], max_length=12),
        ),
    ]
