# Generated by Django 2.2.5 on 2021-04-25 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20210424_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='votes',
        ),
    ]
