# Generated by Django 2.2.5 on 2021-04-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_remove_review_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('PHP', 'PHP'), ('Java', 'Java'), ('C++', 'C++'), ('C', 'C'), ('SQL', 'SQL')], max_length=12),
        ),
    ]
